version: '3.8'

services:
  quiz-app:
    build: .
    ports:
      - "3000:3005"
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: bind mount for development
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
